name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: 
      - '**'
      #- main # Run the workflow when code is pushed to the main branch
      #- master
      #- terraform
  pull_request:
    branches: 
      - main # Run the workflow on pull requests to the main branch
      - master

env:
  AWS_REGION : "ap-south-1" #Change to reflect your Region

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  #AssumeRoleAndCallIdentity:
  #  runs-on: ubuntu-latest
  #  environment: staging
  #  steps:
  #    - name: Git clone the repository
  #      uses: actions/checkout@v3
  #    - name: Set up Terraform
  #      uses: hashicorp/setup-terraform@v2
  #      with:
  #        terraform_version: 1.5.0

  #    - name: Configure AWS Credentials for OIDC
  #      env:
  #        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  #        ROLE_ARN: ${{ secrets.ROLE_ARN }}
  #      run: |
  #        export AWS_REGION=us-west-2

  #        # Use AWS CLI to get temporary credentials via OIDC
  #        TEMP_ROLE=$(aws sts assume-role-with-web-identity --role-arn $ROLE_ARN \
  #          --role-session-name GitHubActionsSession \
  #          --web-identity-token ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }} \
  #          --duration-seconds 3600 \
  #          --output json)

  #        export AWS_ACCESS_KEY_ID=$(echo $TEMP_ROLE | jq -r .Credentials.AccessKeyId)
  #        export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_ROLE | jq -r .Credentials.SecretAccessKey)
  #        export AWS_SESSION_TOKEN=$(echo $TEMP_ROLE | jq -r .Credentials.SessionToken)

  # Job to run `terraform init`
  init:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Git clone the repository
        uses: actions/checkout@3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Setup AWS Credentials using OIDC
        uses: ./actions/setup-aws-oidc/action.yml
        with:
          role_arn: ${{ secrets.ROLE_ARN }}
          aws_region: ap-south-1

      - name: Terraform Init
        run: terraform -chdir=terraform/ init
      - name: Upload Terraform State
        uses: actions/upload-artifacts@v3
        with:
          name: terraform-state
          path: .terraform

  # Job to run `terraform plan`
  plan:
    runs-on: ubuntu-latest
    needs: init  # This job depends on the successful completion of `init`
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Download Terraform State
        uses: actions/download-artifact@v3
        with:
          name: terraform-state

      - name: Setup AWS credentials using OIDC
        uses: ./.github/actions/setup-aws-oidc
        with:
          role_arn: ${{ secrets.ROLE_ARN }}
          aws_region: ap-south-1

      - name: Terraform Plan
        run: terraform -chdir=terraform/ plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan

  # Job to run `terraform apply`
  apply:
    runs-on: ubuntu-latest
    needs: plan  # This job depends on the successful completion of `plan`
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan

      - name: Setup AWS credentials using OIDC
        uses: ./.github/actions/setup-aws-oidc
        with:
          role_arn: ${{ secrets.ROLE_ARN }}
          aws_region: ap-south-1

      - name: Terraform Apply
        run: terraform -chdir=terraform/ apply -auto-approve tfplan